### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by 29k** [29k/rasppistartup#1]
- [ ] how to custom boot screen;
- [x] how to set boot up auto run function;
- [ ] how set IP and wifi;
